"""
Wind Tower Inspection — launcher principal.

Arranca Gazebo con el mundo personalizado (nave + tramo de torre),
spawna el robot Husky+UR5e+Velodyne VLP-16 dentro del tubo y lanza RViz.

Uso:
  ros2 launch wind_tower_bringup simulation.launch.py
  ros2 launch wind_tower_bringup simulation.launch.py rviz:=false
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    IncludeLaunchDescription,
    SetEnvironmentVariable,
    TimerAction,
)
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import EnvironmentVariable, LaunchConfiguration
from launch_ros.actions import Node


ARGUMENTS = [
    DeclareLaunchArgument(
        'rviz',
        default_value='true',
        choices=['true', 'false'],
        description='Lanzar RViz',
    ),
    DeclareLaunchArgument(
        'setup_path',
        default_value=[EnvironmentVariable('HOME'), '/clearpath/'],
        description='Ruta al directorio con robot.yaml de Clearpath',
    ),
    DeclareLaunchArgument('x',   default_value='0.0',    description='Spawn X del robot'),
    DeclareLaunchArgument('y',   default_value='25.0',   description='Spawn Y del robot'),
    DeclareLaunchArgument('z',   default_value='0.3',    description='Spawn Z del robot'),
    DeclareLaunchArgument('yaw', default_value='3.14159', description='Spawn yaw (rad) — mirando al sur hacia el tubo'),
]


def generate_launch_description():
    pkg_clearpath_gz   = get_package_share_directory('clearpath_gz')
    pkg_ros_gz_sim     = get_package_share_directory('ros_gz_sim')
    pkg_wind_sim       = get_package_share_directory('wind_tower_simulation')
    pkg_wind_desc      = get_package_share_directory('wind_tower_description')
    pkg_wind_bringup   = get_package_share_directory('wind_tower_bringup')

    # Sincroniza robot.yaml del repo → ~/clearpath/ antes de que Clearpath lo lea.
    repo_robot_yaml = os.path.join(pkg_wind_bringup, 'config', 'robot.yaml')
    clearpath_dir   = os.path.join(os.path.expanduser('~'), 'clearpath')
    sync_robot_yaml = ExecuteProcess(
        cmd=['bash', '-c',
             f'mkdir -p {clearpath_dir} && '
             f'cp -v {repo_robot_yaml} {clearpath_dir}/robot.yaml'],
        output='screen',
    )

    default_world_file = os.path.join(
        pkg_wind_sim, 'worlds', 'wind_tower_world.sdf')
    declare_world_file = DeclareLaunchArgument(
        'world_file',
        default_value=default_world_file,
        description=(
            'Path to the Gazebo world SDF. Override to load a synthetic '
            'dataset world generated by '
            'wind_tower_perception/generate_synthetic_world.'
        ),
    )
    world_file = LaunchConfiguration('world_file')
    gui_config  = os.path.join(pkg_clearpath_gz, 'config', 'gui.config')
    meshes_path = os.path.join(pkg_wind_desc, 'meshes')

    set_pythonpath = SetEnvironmentVariable(
        name='PYTHONPATH',
        value='/usr/lib/python3/dist-packages:' + os.environ.get('PYTHONPATH', ''),
    )

    packages_paths = [
        os.path.join(p, 'share')
        for p in os.environ.get('AMENT_PREFIX_PATH', '').split(':')
        if p
    ]
    set_gz_resource_path = SetEnvironmentVariable(
        name='GZ_SIM_RESOURCE_PATH',
        value=':'.join([
            os.path.join(pkg_clearpath_gz, 'worlds'),
            os.path.join(pkg_clearpath_gz, 'meshes'),
            meshes_path,
        ] + packages_paths),
    )

    # WSL2: forzar Gazebo a usar TCP en vez de shared memory para evitar
    # "Interrupted system call" que desestabiliza el /clock
    set_gz_ip = SetEnvironmentVariable(name='GZ_IP', value='127.0.0.1')
    set_gz_relay = SetEnvironmentVariable(name='GZ_RELAY', value='127.0.0.1')

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(pkg_ros_gz_sim, 'launch', 'gz_sim.launch.py')
        ),
        launch_arguments=[
            ('gz_args', [world_file, ' -r -v 4 --gui-config ', gui_config]),
        ],
    )

    clock_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='clock_bridge',
        output='screen',
        arguments=['/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock'],
    )

    robot_description_relay = Node(
        package='topic_tools',
        executable='relay',
        name='robot_description_relay',
        arguments=['/robot/robot_description', '/robot_description'],
        parameters=[{'use_sim_time': True}],
        output='screen',
    )

    tf_relay = Node(
        package='topic_tools',
        executable='relay',
        name='tf_relay',
        arguments=['/robot/tf', '/tf'],
        parameters=[{'use_sim_time': True}],
        output='screen',
    )
    tf_static_relay = Node(
        package='wind_tower_bringup',
        executable='tf_static_relay',
        name='tf_static_relay',
        parameters=[{'use_sim_time': True}],
        output='screen',
    )

    # Bridge virador: /turner/cmd_vel (ROS Float64) → gz JointController
    turner_cmd_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='turner_cmd_bridge',
        output='screen',
        arguments=[
            '/model/wind_tower_tube/joint/turner_joint/cmd_vel'
            '@std_msgs/msg/Float64]gz.msgs.Double',
        ],
        remappings=[
            ('/model/wind_tower_tube/joint/turner_joint/cmd_vel', '/turner/cmd_vel'),
        ],
    )

    # Bridge virador: gz joint state → ROS (para ángulo real)
    turner_state_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='turner_state_bridge',
        output='screen',
        arguments=[
            '/world/wind_tower_world/model/wind_tower_tube/joint_state'
            '@sensor_msgs/msg/JointState[gz.msgs.Model',
        ],
        remappings=[
            ('/world/wind_tower_world/model/wind_tower_tube/joint_state',
             '/turner/joint_state'),
        ],
    )

    # Bridge LiDAR 3D Velodyne VLP-16: Gazebo → ROS 2 PointCloud2
    lidar3d_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='lidar3d_bridge',
        output='screen',
        arguments=[
            '/robot/sensors/lidar3d_0/scan/points@sensor_msgs/msg/PointCloud2[gz.msgs.PointCloudPacked',
        ],
        remappings=[
            ('/robot/sensors/lidar3d_0/scan/points', '/velodyne_points'),
        ],
    )

    # Bridge cámara RGB de inspección montada en el TCP del UR5e.
    # ros_gz_image convierte imágenes de Gazebo de forma más robusta que el
    # parameter_bridge genérico; CameraInfo sigue usando ros_gz_bridge.
    inspection_image_bridge = Node(
        package='ros_gz_image',
        executable='image_bridge',
        name='inspection_image_bridge',
        output='screen',
        arguments=[
            '/robot/sensors/inspection_camera/image',
        ],
    )

    inspection_image_relay = Node(
        package='topic_tools',
        executable='relay',
        name='inspection_image_relay',
        output='screen',
        arguments=[
            '/robot/sensors/inspection_camera/image',
            '/inspection/camera/image_raw',
        ],
    )

    inspection_camera_info_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='inspection_camera_info_bridge',
        output='screen',
        arguments=[
            '/robot/sensors/inspection_camera/image/camera_info'
            '@sensor_msgs/msg/CameraInfo[gz.msgs.CameraInfo',
        ],
        remappings=[
            ('/robot/sensors/inspection_camera/image/camera_info',
             '/inspection/camera/camera_info'),
        ],
    )

    robot_spawn = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(pkg_clearpath_gz, 'launch', 'robot_spawn.launch.py')
        ),
        launch_arguments={
            'world':        'wind_tower_world',
            'rviz':         LaunchConfiguration('rviz'),
            'setup_path':   LaunchConfiguration('setup_path'),
            'x':            LaunchConfiguration('x'),
            'y':            LaunchConfiguration('y'),
            'z':            LaunchConfiguration('z'),
            'yaw':          LaunchConfiguration('yaw'),
            'use_sim_time': 'true',
        }.items(),
    )

    turner_node = Node(
        package='wind_tower_bringup',
        executable='turner_node',
        name='turner_node',
        parameters=[{'use_sim_time': True}],
        output='screen',
    )

    # Sobrescribe parámetros del EKF generado por Clearpath para tolerar
    # el clock irregular de Gazebo en WSL2
    ekf_param_override = TimerAction(
        period=10.0,
        actions=[
            ExecuteProcess(
                cmd=['ros2', 'param', 'set', '/robot/ekf_node',
                     'smooth_lagged_data', 'true'],
                output='screen',
            ),
        ],
    )

    # Bridge IMU: Gazebo → ROS2
    imu_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='imu_bridge',
        output='screen',
        arguments=[
            '/robot/sensors/imu_0/data@sensor_msgs/msg/Imu[gz.msgs.IMU',
        ],
    )

    inspection_teleop_limits = TimerAction(
        period=20.0,
        actions=[
            ExecuteProcess(
                cmd=[
                    'ros2', 'param', 'set', '/robot/teleop_twist_joy_node',
                    'scale_linear.x', '0.50',
                ],
                output='screen',
            ),
            ExecuteProcess(
                cmd=[
                    'ros2', 'param', 'set', '/robot/teleop_twist_joy_node',
                    'scale_angular.yaw', '0.40',
                ],
                output='screen',
            ),
            ExecuteProcess(
                cmd=[
                    'ros2', 'param', 'set', '/robot/teleop_twist_joy_node',
                    'scale_linear_turbo.x', '0.90',
                ],
                output='screen',
            ),
            ExecuteProcess(
                cmd=[
                    'ros2', 'param', 'set', '/robot/teleop_twist_joy_node',
                    'scale_angular_turbo.yaw', '0.70',
                ],
                output='screen',
            ),
        ],
    )

    return LaunchDescription(ARGUMENTS + [
        declare_world_file,
        sync_robot_yaml,
        set_pythonpath,
        set_gz_resource_path,
        set_gz_ip,
        set_gz_relay,
        gz_sim,
        clock_bridge,
        turner_cmd_bridge,
        turner_state_bridge,
        lidar3d_bridge,
        inspection_image_bridge,
        inspection_image_relay,
        inspection_camera_info_bridge,
        robot_description_relay,
        tf_relay,
        tf_static_relay,
        turner_node,
        imu_bridge,
        robot_spawn,
        ekf_param_override,
        inspection_teleop_limits,
    ])
