"""Launch the MoveIt ``move_group`` for the UR5e inspection arm.

The robot model is **not** shipped inside this package: the full Husky + UR5e
+ inspection-camera description is generated by the Clearpath tooling into the
setup directory (``~/clearpath`` by default), as ``robot.urdf.xacro`` and
``robot.srdf``. This launch consumes those two files plus the MoveIt YAMLs in
this package's ``config/``.

Usage::

    # 1) Simulation must already be running (provides /robot/joint_states and
    #    the /robot/arm_0_joint_trajectory_controller):
    ros2 launch wind_tower_bringup simulation.launch.py

    # 2) Then bring up MoveIt:
    ros2 launch wind_tower_arm_control move_group.launch.py

Arguments:
    setup_path     Clearpath setup dir holding robot.urdf.xacro + robot.srdf.
    use_rviz       Launch RViz with the MotionPlanning panel (default true).
    use_sim_time   Use the Gazebo clock (default true).
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from moveit_configs_utils import MoveItConfigsBuilder


def _launch_setup(context, *args, **kwargs):
    setup_path = os.path.expanduser(
        LaunchConfiguration('setup_path').perform(context))
    use_rviz = LaunchConfiguration('use_rviz')
    use_sim_time = (
        LaunchConfiguration('use_sim_time').perform(context).lower() == 'true')
    use_octomap = (
        LaunchConfiguration('use_octomap').perform(context).lower() == 'true')
    octomap_frame = LaunchConfiguration('octomap_frame').perform(context)
    octomap_resolution = float(
        LaunchConfiguration('octomap_resolution').perform(context))

    pkg_share = get_package_share_directory('wind_tower_arm_control')
    config_dir = os.path.join(pkg_share, 'config')

    urdf_xacro = os.path.join(setup_path, 'robot.urdf.xacro')
    srdf_file = os.path.join(setup_path, 'robot.srdf')

    for required in (urdf_xacro, srdf_file):
        if not os.path.isfile(required):
            raise RuntimeError(
                f'Required robot file not found: {required}\n'
                'Generate the Clearpath description first, or pass '
                'setup_path:=<dir containing robot.urdf.xacro and robot.srdf>.'
            )

    builder = (
        MoveItConfigsBuilder('a200-0000', package_name='wind_tower_arm_control')
        .robot_description(file_path=urdf_xacro)
        .robot_description_semantic(file_path=srdf_file)
        .robot_description_kinematics(
            file_path=os.path.join(config_dir, 'kinematics.yaml'))
        .joint_limits(
            file_path=os.path.join(config_dir, 'joint_limits.yaml'))
        .trajectory_execution(
            file_path=os.path.join(config_dir, 'moveit_controllers.yaml'))
        .planning_pipelines(
            pipelines=['ompl'], default_planning_pipeline='ompl')
        .planning_scene_monitor(
            publish_planning_scene=True,
            publish_geometry_updates=True,
            publish_state_updates=True,
            publish_transforms_updates=True,
        )
    )
    if use_octomap:
        # Wire the Velodyne LiDAR into the occupancy_map_monitor so the
        # planner sees the tube wall (and anything else in front of it) as
        # collision geometry.
        builder = builder.sensors_3d(
            file_path=os.path.join(config_dir, 'sensors_3d.yaml'))
    moveit_config = builder.to_moveit_configs()

    extra_octomap_params = (
        {'octomap_frame': octomap_frame,
         'octomap_resolution': octomap_resolution}
        if use_octomap else {}
    )

    move_group_node = Node(
        package='moveit_ros_move_group',
        executable='move_group',
        name='move_group',
        output='screen',
        parameters=[
            moveit_config.to_dict(),
            {'use_sim_time': use_sim_time},
            {'publish_robot_description': True,
             'publish_robot_description_semantic': True},
            extra_octomap_params,
        ],
        # Clearpath's joint_state_broadcaster publishes the full robot joint
        # state (platform + arm) on /robot/platform/joint_states, so the
        # planning scene monitor's current-state monitor must subscribe there.
        remappings=[('/joint_states', '/robot/platform/joint_states')],
    )

    rviz_node = Node(
        package='rviz2',
        executable='rviz2',
        name='moveit_rviz',
        output='screen',
        arguments=['-d', os.path.join(config_dir, 'moveit.rviz')],
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.robot_description_kinematics,
            moveit_config.planning_pipelines,
            moveit_config.joint_limits,
            {'use_sim_time': use_sim_time},
        ],
        condition=IfCondition(use_rviz),
    )

    return [move_group_node, rviz_node]


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument(
            'setup_path',
            default_value=os.path.join(
                os.environ.get('HOME', '~'), 'clearpath'),
            description='Clearpath setup dir with robot.urdf.xacro + robot.srdf.',
        ),
        DeclareLaunchArgument(
            'use_rviz', default_value='true',
            description='Launch RViz with the MoveIt MotionPlanning panel.',
        ),
        DeclareLaunchArgument(
            'use_sim_time', default_value='true',
            description='Use the Gazebo /clock.',
        ),
        DeclareLaunchArgument(
            'use_octomap', default_value='true',
            description=(
                'Wire the Velodyne point cloud into the MoveIt occupancy_map '
                'monitor so the planner avoids what the LiDAR sees.'),
        ),
        DeclareLaunchArgument(
            'octomap_frame', default_value='odom',
            description='Fixed frame in which the octomap is built.',
        ),
        DeclareLaunchArgument(
            'octomap_resolution', default_value='0.05',
            description='Octomap voxel size in metres (smaller = finer + slower).',
        ),
        OpaqueFunction(function=_launch_setup),
    ])
