serial_number: a200-0000
version: 0

system:
  hosts:
    - hostname: wind-tower-inspector
      ip: 192.168.131.1
  ros2:
    namespace: robot

platform:
  attachments:
    - name: front_bumper
      type: a200.bumper
      parent: front_bumper_mount
    - name: rear_bumper
      type: a200.bumper
      parent: rear_bumper_mount
    - name: top_plate
      type: a200.top_plate
      model: pacs
  extras:
    urdf:
      package: wind_tower_description
      path: urdf/inspection_camera_lighting.urdf.xacro

manipulators:
  arms:
    - model: universal_robots
      parent: default_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ur_type: ur5e
      robot_ip: 192.168.131.40
      headless_mode: false
      kinematics_parameters_file: "$(find ur_description)/config/ur5e/default_kinematics.yaml"
      poses:
        - name: home
          joints: [0.0, -1.57, 1.57, -1.57, -1.57, 0.0]

sensors:
  imu:
    - model: phidgets_spatial
      urdf_enabled: true
      launch_enabled: false
      parent: base_link
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
  lidar3d:
    - model: velodyne_lidar
      urdf_enabled: true
      launch_enabled: false
      parent: top_plate_link
      xyz: [0.25, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
  lidar2d:
    - model: hokuyo_ust
      urdf_enabled: false
      launch_enabled: false
      parent: front_bumper_mount
      xyz: [0.0, 0.0, 0.1]
      rpy: [0.0, 0.0, 0.0]
