"""Train a YOLOv8 detector on the autogenerated wind-tower defect dataset.

Thin wrapper around ``ultralytics.YOLO.train`` with project-friendly defaults.
The dataset is expected to follow YOLO's standard layout:

    <dataset_root>/
      images/train/*.jpg
      images/val/*.jpg
      labels/train/*.txt
      labels/val/*.txt
      dataset.yaml       (paths + class names)

If you ran ``synthetic_capture_node`` with ``output_dir=~/wind_tower_dataset``
and copied the package's ``config/dataset.yaml`` to that directory, the
defaults below already point at the right place.

Usage::

    python -m wind_tower_perception.scripts.train_yolo \\
        --dataset ~/wind_tower_dataset/dataset.yaml \\
        --epochs 80 --imgsz 640 --weights yolov8n.pt
"""

import argparse
import os
import sys


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dataset', required=True,
                        help='Path to the YOLO dataset YAML.')
    parser.add_argument('--weights', default='yolov8n.pt',
                        help='Pretrained weights to start from. '
                             'Use "yolov8s.pt" for a heavier model.')
    parser.add_argument('--epochs', type=int, default=80)
    parser.add_argument('--imgsz', type=int, default=640)
    parser.add_argument('--batch', type=int, default=16)
    parser.add_argument('--device', default='0',
                        help='Device passed to ultralytics. "0" for first GPU, '
                             '"cpu" to force CPU.')
    parser.add_argument('--project', default='~/wind_tower_runs',
                        help='Ultralytics output project directory.')
    parser.add_argument('--name', default='wind_tower_defects',
                        help='Run name within --project.')
    parser.add_argument('--patience', type=int, default=20,
                        help='Early-stopping patience (epochs).')
    args = parser.parse_args(argv)

    try:
        from ultralytics import YOLO
    except ImportError:
        print(
            '[train_yolo] `ultralytics` is not installed. Install with: '
            '`pip install ultralytics` (also installs torch CPU wheels by '
            'default; for CUDA see https://docs.ultralytics.com).',
            file=sys.stderr,
        )
        sys.exit(1)

    dataset_yaml = os.path.expanduser(args.dataset)
    if not os.path.isfile(dataset_yaml):
        print(f'[train_yolo] dataset YAML not found: {dataset_yaml}',
              file=sys.stderr)
        sys.exit(1)

    project_dir = os.path.expanduser(args.project)
    os.makedirs(project_dir, exist_ok=True)

    model = YOLO(args.weights)
    results = model.train(
        data=dataset_yaml,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=project_dir,
        name=args.name,
        patience=args.patience,
        exist_ok=True,
    )

    best_pt = os.path.join(project_dir, args.name, 'weights', 'best.pt')
    print(f'[train_yolo] training complete.')
    print(f'[train_yolo] best weights: {best_pt}')
    print(
        '[train_yolo] launch the detector with:\n'
        f'  ros2 run wind_tower_perception detector \\\n'
        f'      --ros-args -p backend:=yolo -p yolo.model_path:={best_pt}'
    )
    return results


if __name__ == '__main__':
    main()
